name: Close and Release Repository
on: workflow_dispatch

jobs:
  publish:
    runs-on: [ubuntu-latest]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Close and Release Staging Repository
      run: ./gradlew closeAndReleaseStagingRepository
      env:
        ORG_GRADLE_PROJECT_NEXUS_USERNAME: ${{ secrets.ORG_GRADLE_PROJECT_NEXUS_USERNAME }}
        ORG_GRADLE_PROJECT_NEXUS_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_NEXUS_PASSWORD }}
